### ISSUE TITLE
some questions with bluepool

### ISSUE THREAD

**Issue by bi-kai** [chiabluepool/bluepool#3]
1.  where to fill my wallet address?
2. files ploted with official software cannot be used in bluepool.
enmm...

**Comment by aj10017** [comment]
If you plot with the official chia client you will need to fill in the farmer and pool key with the bluepool keys and plot with CLI. you will still need to harvest using the bluepool harvester, but with this method, your plotters can create bluepool plots using the official client

**Comment by chiabluepool** [comment]
Old plots are supported now, but only through a win/mac installer. This version is closed source because using your own keys makes it possible to cheat the pool by submitting partials that are not winning and keeping the ones that are winning. (This is the issue HPool had before it went on a banning spree)
